### ISSUE TITLE
interactive book with javascript error

### ISSUE THREAD

**Issue by pevaristo** [tunapanda/h5p-standalone#123]
Hi, 

The interactive book seem to have a javascript error. If you try the interactive book example from the h5p.org website, you will get the following Javascript error on both Chrome and Firefox:

frame.bundle.js:2 jQuery.Deferred exception: Cannot assign to read only property 'prototype' of function 'function i(t,r){var n,a=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{};at(this,i);var s=ut(n=o.call(...<omitted>...n}' TypeError: Cannot assign to read only property 'prototype' of function 'function i(t,r){var n,a=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{};at(this,i);var s=ut(n=o.call(...<omitted>...n}'
    at i.newRunnable (http://localhost:8081/assets/frame.bundle.js:2:117728)
    at HTMLDivElement.<anonymous> (http://localhost:8081/assets/frame.bundle.js:2:108627)
    at Function.each (http://localhost:8081/assets/frame.bundle.js:2:15395)
    at P.fn.init.each (http://localhost:8081/assets/frame.bundle.js:2:13875)
    at i.init (http://localhost:8081/assets/frame.bundle.js:2:107649)
    at HTMLDocument.<anonymous> (http://localhost:8081/assets/frame.bundle.js:2:137900)
    at l (http://localhost:8081/assets/frame.bundle.js:2:42385)
    at u (http://localhost:8081/assets/frame.bundle.js:2:42687) undefined
P.Deferred.exceptionHook @ frame.bundle.js:2
u @ frame.bundle.js:2
setTimeout (async)
(anonymous) @ frame.bundle.js:2
u @ frame.bundle.js:2
fireWith @ frame.bundle.js:2
fire @ frame.bundle.js:2
u @ frame.bundle.js:2
fireWith @ frame.bundle.js:2
ready @ frame.bundle.js:2
$ @ frame.bundle.js:2
frame.bundle.js:2 Uncaught TypeError: Cannot assign to read only property 'prototype' of function 'function i(t,r){var n,a=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{};at(this,i);var s=ut(n=o.call(...<omitted>...n}'
    at i.newRunnable (frame.bundle.js:2:117728)
    at HTMLDivElement.<anonymous> (frame.bundle.js:2:108627)
    at Function.each (frame.bundle.js:2:15395)
    at P.fn.init.each (frame.bundle.js:2:13875)
    at i.init (frame.bundle.js:2:107649)
    at HTMLDocument.<anonymous> (frame.bundle.js:2:137900)
    at l (frame.bundle.js:2:42385)
    at u (frame.bundle.js:2:42687)

**Comment by pevaristo** [comment]
#119
