### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by nadavkav** [tunapanda/h5p-standalone#24]
gulp demo
[23:10:43] Using gulpfile /var/www/html/h5p/h5p-standalone/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by marbaque** [comment]
Thanks I can now run the demo, however it is not displaying my content, which I saved in the workspace folder...

**Comment by nadavkav** [comment]
Eventually, I did not use this method for H5P content development.
I installed https://github.com/h5p/h5p-cli and used the command "h5p server"
and to get started, I used: https://h5p.org/h5p-cli-guide#getcmd ("h5p get <library>")

**Comment by Jakeii** [comment]
Thanks for this, I've updated the readme
