### ISSUE TITLE
Only dependencies declared in h5p.json loaded

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/h5p-standalone#8]
For all the cases I've tested until now this has worked fine, but now with a certain H5P.QuestionSet based H5P, there seem to be deeper levels of dependencies that need to be loaded.

For Example:
H5P.QuestionSet depends on H5P.JoubelUI which depends on H5P.Transition

but H5P.Transition isn't declared in h5p.json so it's not loaded.

**Comment by daverage** [comment]
Yes, having this issue with the drag and drop game type it seems

**Comment by Jakeii** [comment]
Hi @daverage would you mind testing #10, it should fix the problem.

**Comment by daverage** [comment]
Mmm @Jakeii - it may be a different issue. I get the console errors when I run a drag and drop type


http://192.168.204.2:8080/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
dragquestion.js:169 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at dragquestion.js:169
    at dragquestion.js:1632
dragquestion.js:1050 Uncaught TypeError: Cannot set property 'originalPosition' of undefined
    at Z.fn.init.revert (http://192.168.204.2:8080/mission2/workspace/H5P.DragQuestion-1.7/js/dragquestion.js:1050:81)
    at $.(anonymous function).(anonymous function)._mouseStop (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:1215:195)
    at $.(anonymous function).(anonymous function)._mouseStop (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:404:25)
    at $.(anonymous function).(anonymous function)._mouseUp (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:961:9)
    at $.(anonymous function).(anonymous function)._mouseUp (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:404:25)
    at $.(anonymous function).(anonymous function)._mouseUp (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:1241:40)
    at $.(anonymous function).(anonymous function)._mouseUp (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:404:25)
    at HTMLDocument._mouseUpDelegate (http://192.168.204.2:8080/mission2/workspace/jQuery.ui-1.10/h5p-jquery-ui.js:917:16)
    at HTMLDocument.dispatch (http://192.168.204.2:8080/mission2/js/h5p-standalone-frame.min.js:2:14540)
    at HTMLDocument.v.handle (http://192.168.204.2:8080/mission2/js/h5p-standalone-frame.min.js:2:11315)
revert @ dragquestion.js:1050
_mouseStop @ h5p-jquery-ui.js:1215
(anonymous) @ h5p-jquery-ui.js:404
_mouseUp @ h5p-jquery-ui.js:961
(anonymous) @ h5p-jquery-ui.js:404
_mouseUp @ h5p-jquery-ui.js:1241
(anonymous) @ h5p-jquery-ui.js:404
_mouseUpDelegate @ h5p-jquery-ui.js:917
dispatch @ h5p-standalone-frame.min.js:2
v.handle @ h5p-standalone-frame.min.js:2

**Comment by Jakeii** [comment]
In that case could you send the offending H5P to jake@tunapanda.org?

**Comment by ajblum** [comment]
Greetings.

I'm seeing this as well with the drag and drop h5p content type:

```
dragquestion.js:171 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at dragquestion.js:171
    at dragquestion.js:1680
```
Then, after trying to drag one of the elements:

```
dragquestion.js:1098 Uncaught TypeError: Cannot set property 'originalPosition' of undefined
    at Z.fn.init.revert (http://SNIP/files/h5p/drag-n-drop/H5P.DragQuestion-1.10/js/dragquestion.js:1098:81)
    at $.(anonymous function).(anonymous function)._mouseStop (http://SNIP/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:1218:195)
    at $.(anonymous function).(anonymous function)._mouseStop (http://SNIP/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:404:25)
    at $.(anonymous function).(anonymous function)._mouseUp (http://SNIP/cee-xx-348/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:964:9)
    at $.(anonymous function).(anonymous function)._mouseUp (http://SNIP/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:404:25)
    at $.(anonymous function).(anonymous function)._mouseUp (http://SNIP/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:1244:40)
    at $.(anonymous function).(anonymous function)._mouseUp (http://SNIP/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:404:25)
    at HTMLDocument._mouseUpDelegate (http://SNIP/files/h5p/drag-n-drop/jQuery.ui-1.10/h5p-jquery-ui.js:917:16)
    at HTMLDocument.dispatch (http://SNIP/files/h5p/js/h5p-standalone-frame.min.js:2:14540)
    at HTMLDocument.v.handle (http://SNIP/files/h5p/js/h5p-standalone-frame.min.js:2:11315)
```

Other H5p content types (like hotspot and presentation are working as expected).

@Jakeii any ideas how to resolve ?
